### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'zeta.structs.attn_layers'

### ISSUE THREAD

**Issue by Math312** [kyegomez/zeta#48]
My zetascale version is:
zetascale                 1.2.4
When I  run the code in 
https://github.com/kyegomez/Fuyu/tree/main/fuyu
The error is:

Traceback (most recent call last):
  File "/mnt/sda/shaoyanli/fuyu/Fuyu/example.py", line 2, in <module>
    from fuyu.model import Fuyu
  File "/mnt/sda/shaoyanli/fuyu/Fuyu/fuyu/__init__.py", line 1, in <module>
    from fuyu.model import Fuyu
  File "/mnt/sda/shaoyanli/fuyu/Fuyu/fuyu/model.py", line 3, in <module>
    from zeta.structs import AutoregressiveWrapper, Decoder, Transformer
  File "/mnt/sda/anaconda3/envs/fuyu/lib/python3.10/site-packages/zeta/__init__.py", line 5, in <module>
    from zeta.nn import *  # noqa: F403, E402
  File "/mnt/sda/anaconda3/envs/fuyu/lib/python3.10/site-packages/zeta/nn/__init__.py", line 1, in <module>
    from zeta.nn.attention import *
  File "/mnt/sda/anaconda3/envs/fuyu/lib/python3.10/site-packages/zeta/nn/attention/__init__.py", line 14, in <module>
    from zeta.nn.attention.mixture_attention import (
  File "/mnt/sda/anaconda3/envs/fuyu/lib/python3.10/site-packages/zeta/nn/attention/mixture_attention.py", line 8, in <module>
    from zeta.models.vit import exists
  File "/mnt/sda/anaconda3/envs/fuyu/lib/python3.10/site-packages/zeta/models/__init__.py", line 3, in <module>
    from zeta.models.andromeda import Andromeda
  File "/mnt/sda/anaconda3/envs/fuyu/lib/python3.10/site-packages/zeta/models/andromeda.py", line 4, in <module>
    from zeta.structs.auto_regressive_wrapper import AutoregressiveWrapper
  File "/mnt/sda/anaconda3/envs/fuyu/lib/python3.10/sit/mnt/sda/anaconda3/envs/fuyu/lib/python3.10/site-packages/zeta/structs/e-packages/zeta/structs/__init__.py", line 4, in <module>
    from zeta.structs.hierarchical_transformer import (
  File "/mnt/sda/anaconda3/envs/fuyu/lib/python3.10/site-packages/zeta/structs/hierarchical_transformer.py", line 13, in <module>
    from zeta.structs.attn_layers import rotate_half
ModuleNotFoundError: No module named 'zeta.structs.attn_layers'

so I go to the package path of zeta, but I can't find the File zeta/structs/attn_layers

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/zeta/issues/48">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/zeta/issues/48/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/zeta/issues/48/pledge.svg">
</picture>
</a>

**Comment by Math312** [comment]
These are the files in zeta/structs
(fuyu) lab414@lab414:/mnt/sda/anaconda3/envs/fuyu/lib/python3.10/site-packages/zeta/structs$ ls -alh
total 160K
drwxrwxr-x  3 lab414 lab414 4.0K 12月 24 11:46 .
drwxrwxr-x 15 lab414 lab414 4.0K 12月 24 11:45 ..
-rw-rw-r--  1 lab414 lab414  12K 12月 24 11:24 auto_regressive_wrapper.py
-rw-rw-r--  1 lab414 lab414 3.5K 12月 24 11:24 clip_encoder.py
-rw-rw-r--  1 lab414 lab414 6.6K 12月 24 11:24 efficient_net.py
-rw-rw-r--  1 lab414 lab414 3.2K 12月 24 11:24 encoder_decoder.py
-rw-rw-r--  1 lab414 lab414  28K 12月 24 11:24 hierarchical_transformer.py
-rw-rw-r--  1 lab414 lab414 1.3K 12月 24 11:24 __init__.py
-rw-rw-r--  1 lab414 lab414 5.8K 12月 24 11:24 local_transformer.py
-rw-rw-r--  1 lab414 lab414 1.7K 12月 24 11:24 multi_modal_projector.py
drwxrwxr-x  2 lab414 lab414 4.0K 12月 24 11:24 __pycache__
-rw-rw-r--  1 lab414 lab414  11K 12月 24 11:24 simple_transformer.py
-rw-rw-r--  1 lab414 lab414 4.4K 12月 24 11:24 transformer_block.py
-rw-rw-r--  1 lab414 lab414  53K 12月 24 11:24 transformer.py

**Comment by kyegomez** [comment]
@Math312 I've just updated it and fixed these errors remind me if they are any more errors please
